import dbConnect from "@/lib/mongodb";
import Category from "@/models/Category";
import Product from "@/models/Product";
import { NextResponse } from "next/server";

export async function GET() {
  if (process.env.NODE_ENV === "production" && process.env.ENABLE_DB_SEED !== "true") {
    return NextResponse.json({ message: "Seed endpoint is disabled in production." }, { status: 403 });
  }

  try {
    await dbConnect();

    await Product.deleteMany({});
    await Category.deleteMany({});

    const categoriesData = [
      { name: "Development Boards", slug: "development-boards", icon: "CommandLineIcon", featured: true },
      { name: "Electronics Components", slug: "electronics-components", icon: "CpuChipIcon", featured: true },
      { name: "Motors & Drivers", slug: "motors-drivers", icon: "Cog6ToothIcon", featured: true },
      { name: "Wireless Modules", slug: "wireless-modules", icon: "WifiIcon", featured: true },
      { name: "Display Modules", slug: "display-modules", icon: "ComputerDesktopIcon" },
      { name: "Power & Batteries", slug: "power-batteries", icon: "BoltIcon", featured: true },
      { name: "Sensors", slug: "sensors", icon: "BeakerIcon", featured: true },
      { name: "Tools & Equipment", slug: "tools-equipment", icon: "WrenchScrewdriverIcon" },
      { name: "Cables & Connectors", slug: "cables-connectors", icon: "LinkIcon" },
      { name: "LEDs & Lighting", slug: "leds-lighting", icon: "LightBulbIcon" },
      { name: "Robotics & Automation", slug: "robotics-automation", icon: "CubeTransparentIcon" },
      { name: "DIY Electronics Kits", slug: "diy-kits", icon: "PuzzlePieceIcon" },
      { name: "PCB & Prototyping", slug: "pcb-prototyping", icon: "CircleStackIcon" },
      { name: "Drones & Accessories", slug: "drones-accessories", icon: "RocketLaunchIcon" },
      { name: "IoT Devices", slug: "iot-devices", icon: "GlobeAltIcon" },
      { name: "RC Models & Vehicles", slug: "rc-models-vehicles", icon: "TruckIcon" },
      { name: "Solar", slug: "solar", icon: "SunIcon" },
      { name: "Test & Measurement", slug: "test-measurement", icon: "ChartBarIcon" },
      { name: "Switches & Relays", slug: "switches-relays", icon: "AdjustmentsHorizontalIcon" },
      { name: "Audio Components", slug: "audio-components", icon: "SpeakerWaveIcon" },
      { name: "Industrial Electronics", slug: "industrial-electronics", icon: "BuildingOffice2Icon" },
      { name: "RC Transmitters & Receivers", slug: "rc-transmitters-receivers", icon: "SignalIcon" },
      { name: "Electrical Accessories", slug: "electrical-accessories", icon: "SparklesIcon" },
    ];

    const createdCategories = await Category.insertMany(categoriesData);
    const cat = (slug: string) => createdCategories.find((c) => c.slug === slug)?._id ?? null;

    const productsData = [
      // ── DEVELOPMENT BOARDS ─────────────────────────────────────
      {
        name: "Arduino Uno R3",
        description: "The most popular microcontroller board based on ATmega328P. 14 digital I/O pins (6 PWM), 6 analog inputs, 16 MHz crystal oscillator, USB connection. Perfect for beginners and pros alike.",
        price: 12.99,
        discount: 0,
        stock: 85,
        image: "https://m.media-amazon.com/images/I/61H1ia-8hrL._AC_SX679_.jpg",
        featured: true,
        category: cat("development-boards"),
        tags: ["arduino", "uno", "atmega328p", "microcontroller"],
        specs: { MCU: "ATmega328P", "Flash Memory": "32 KB", "Operating Voltage": "5V", "Digital I/O": "14 pins" },
      },
      {
        name: "Arduino Nano V3",
        description: "Compact breadboard-friendly microcontroller board with ATmega328P. Identical to the Uno but in a mini DIP form factor. Includes mini-USB port.",
        price: 6.99,
        discount: 10,
        stock: 120,
        image: "https://m.media-amazon.com/images/I/71B9hYbAFnL._AC_SX679_.jpg",
        featured: true,
        category: cat("development-boards"),
        tags: ["arduino", "nano", "atmega328p", "compact"],
        specs: { MCU: "ATmega328P", "Flash Memory": "32 KB", "Operating Voltage": "5V", Dimensions: "18×45 mm" },
      },
      {
        name: "Arduino Mega 2560 R3",
        description: "High-performance board with ATmega2560, featuring 54 digital I/O pins, 16 analog inputs, 4 UARTs, and 256 KB flash. Ideal for complex robotics and CNC projects.",
        price: 19.99,
        discount: 5,
        stock: 40,
        image: "https://m.media-amazon.com/images/I/71z5MkiI27L._AC_SX679_.jpg",
        featured: false,
        category: cat("development-boards"),
        tags: ["arduino", "mega", "atmega2560", "robotics"],
        specs: { MCU: "ATmega2560", "Flash Memory": "256 KB", "Digital I/O": "54 pins", UART: "4 ports" },
      },
      {
        name: "Raspberry Pi 4 Model B — 4GB",
        description: "Flagship single-board computer with quad-core Cortex-A72, 4GB LPDDR4 RAM, dual 4K HDMI, USB 3.0, Gigabit Ethernet, and WiFi/BT5. Perfect for edge AI, media center, and robotics controller.",
        price: 68.00,
        discount: 0,
        stock: 18,
        image: "https://m.media-amazon.com/images/I/7lXDHxeXO5L._AC_SX679_.jpg",
        featured: true,
        category: cat("development-boards"),
        tags: ["raspberry pi", "rpi4", "linux", "sbc"],
        specs: { CPU: "Cortex-A72 1.8GHz", RAM: "4GB LPDDR4", USB: "2× USB3 + 2× USB2", Connectivity: "WiFi 5 + BT 5.0" },
      },
      {
        name: "ESP32 WROOM DevKit V1",
        description: "Dual-core 240 MHz Xtensa processor with built-in WiFi 802.11 b/g/n and Bluetooth 4.2. 38-pin development board ideal for IoT, home automation, and wireless sensor nodes.",
        price: 5.49,
        discount: 0,
        stock: 200,
        image: "https://m.media-amazon.com/images/I/61BmpFxwnFL._AC_SX679_.jpg",
        featured: true,
        category: cat("development-boards"),
        tags: ["esp32", "wifi", "bluetooth", "iot"],
        specs: { CPU: "Xtensa LX6 240 MHz", Flash: "4 MB", Connectivity: "WiFi + BT 4.2", GPIO: "34 pins" },
      },
      {
        name: "NodeMCU ESP8266 V3",
        description: "Low-cost WiFi microcontroller module with full TCP/IP stack. 11 digital GPIO pins, 1 analog, built-in USB-to-serial, ideal for smart home and IoT sensor nodes.",
        price: 3.49,
        discount: 0,
        stock: 250,
        image: "https://m.media-amazon.com/images/I/61zf0mfHJAL._AC_SX679_.jpg",
        featured: false,
        category: cat("development-boards"),
        tags: ["esp8266", "nodemcu", "wifi", "iot"],
        specs: { CPU: "L106 80 MHz", Flash: "4 MB", WiFi: "802.11 b/g/n", GPIO: "11 digital" },
      },
      {
        name: "Raspberry Pi Pico W",
        description: "Compact RP2040-based microcontroller with onboard WiFi. Dual-core ARM Cortex-M0+ at 133 MHz, 264 KB SRAM, 26 GPIO pins. Ideal for wearables and compact embedded projects.",
        price: 7.99,
        discount: 0,
        stock: 95,
        image: "https://m.media-amazon.com/images/I/61byjBRzUKL._AC_SX679_.jpg",
        featured: true,
        category: cat("development-boards"),
        tags: ["raspberry pi", "pico", "rp2040", "wifi"],
        specs: { CPU: "Dual-core Cortex-M0+ 133 MHz", SRAM: "264 KB", Flash: "2 MB", GPIO: "26 pins" },
      },

      // ── SENSORS ────────────────────────────────────────────────
      {
        name: "HC-SR04 Ultrasonic Distance Sensor",
        description: "Non-contact ranging module with 2 cm–4 m range and ±3 mm accuracy. Works at 5V, ultra-low current. Standard choice for obstacle avoidance robots.",
        price: 1.79,
        discount: 0,
        stock: 300,
        image: "https://m.media-amazon.com/images/I/61SrE2ZQSCL._SX522_.jpg",
        featured: true,
        category: cat("sensors"),
        tags: ["ultrasonic", "hcsr04", "distance", "sensor"],
        specs: { "Sensing Range": "2 – 400 cm", Accuracy: "±3 mm", "Supply Voltage": "5V", Current: "15 mA" },
      },
      {
        name: "DHT22 Temperature & Humidity Sensor",
        description: "High-accuracy digital sensor measuring −40 °C to +80 °C with ±0.5 °C accuracy and 0–100% RH humidity. Single-wire digital interface.",
        price: 4.99,
        discount: 0,
        stock: 180,
        image: "https://m.media-amazon.com/images/I/51YzN4bkXxL._AC_SX679_.jpg",
        featured: false,
        category: cat("sensors"),
        tags: ["dht22", "temperature", "humidity", "sensor"],
        specs: { "Temp Range": "−40°C to +80°C", "Temp Accuracy": "±0.5°C", "Humidity Range": "0–100% RH", Interface: "Single-wire" },
      },
      {
        name: "MPU-6050 6-Axis Gyro + Accelerometer",
        description: "3-axis gyroscope and 3-axis accelerometer on a single chip with onboard DMP. Communicates via I2C. Used in drones, robots, and motion tracking systems.",
        price: 3.49,
        discount: 0,
        stock: 160,
        image: "https://m.media-amazon.com/images/I/619zZzJQb5L._AC_SX679_.jpg",
        featured: false,
        category: cat("sensors"),
        tags: ["mpu6050", "gyroscope", "accelerometer", "imu"],
        specs: { Axes: "6 (3 gyro + 3 accel)", Interface: "I2C", "Supply Voltage": "3.3V – 5V", "Gyro Range": "±250–2000°/s" },
      },
      {
        name: "BMP280 Barometric Pressure & Temperature Sensor",
        description: "Ultra-low power barometric pressure sensor with temperature compensation. I2C/SPI interface. ±1 hPa absolute accuracy, ideal for weather stations and altitude estimation.",
        price: 2.99,
        discount: 0,
        stock: 140,
        image: "https://m.media-amazon.com/images/I/61wuS8XHCKL._AC_SX679_.jpg",
        featured: false,
        category: cat("sensors"),
        tags: ["bmp280", "pressure", "barometer", "sensor"],
        specs: { "Pressure Range": "300–1100 hPa", Accuracy: "±1 hPa", Interface: "I2C / SPI", "Supply Voltage": "3.3V" },
      },
      {
        name: "PIR Motion Sensor Module HC-SR501",
        description: "Passive infrared motion detector with adjustable sensitivity and delay time. 3–7 m detection range and 120° viewing angle. Perfect for security systems and smart lighting.",
        price: 2.49,
        discount: 0,
        stock: 220,
        image: "https://m.media-amazon.com/images/I/61jkMz4BQTL._AC_SX679_.jpg",
        featured: false,
        category: cat("sensors"),
        tags: ["pir", "motion", "infrared", "hcsr501"],
        specs: { "Detection Range": "3–7 m", "Viewing Angle": "120°", "Supply Voltage": "5–20V", Delay: "Adjustable 5s–5min" },
      },

      // ── MOTORS & DRIVERS ───────────────────────────────────────
      {
        name: "SG90 Micro Servo Motor",
        description: "Lightweight 9g micro servo with 180° rotation, 1.8 kg·cm torque, and PWM control. Comes with mounting hardware and control horns. Great for RC, robot arms, and pan-tilt kits.",
        price: 2.49,
        discount: 0,
        stock: 350,
        image: "https://m.media-amazon.com/images/I/51Mk8kSCJML._AC_SX679_.jpg",
        featured: true,
        category: cat("motors-drivers"),
        tags: ["sg90", "servo", "micro", "pwm"],
        specs: { Torque: "1.8 kg·cm", Rotation: "0–180°", Weight: "9 g", "Operating Voltage": "4.8–6V" },
      },
      {
        name: "MG996R Metal Gear Servo Motor",
        description: "High-torque 13 kg·cm metal gear servo with dual ball bearings. Ideal for robotic joints, RC car steering, and heavy-duty pan-tilt systems.",
        price: 7.49,
        discount: 8,
        stock: 90,
        image: "https://m.media-amazon.com/images/I/61AHjPCvJoL._AC_SX679_.jpg",
        featured: true,
        category: cat("motors-drivers"),
        tags: ["mg996r", "servo", "metal gear", "high torque"],
        specs: { Torque: "13 kg·cm", Gear: "Metal", Weight: "55 g", "Operating Voltage": "4.8–7.2V" },
      },
      {
        name: "L298N Dual H-Bridge Motor Driver",
        description: "Dual H-bridge motor driver IC able to drive 2 DC motors or 1 stepper motor up to 2A per channel. Onboard 5V regulator, power LED, and enable jumpers.",
        price: 2.49,
        discount: 0,
        stock: 180,
        image: "https://m.media-amazon.com/images/I/61Bxk08nVNL._AC_SX679_.jpg",
        featured: false,
        category: cat("motors-drivers"),
        tags: ["l298n", "motor driver", "h-bridge", "dc motor"],
        specs: { Channels: "2 DC / 1 Stepper", "Max Current": "2A per channel", "Supply Voltage": "5–35V", Logic: "5V" },
      },
      {
        name: "28BYJ-48 Stepper Motor + ULN2003 Driver",
        description: "5V 4-phase unipolar stepper motor with ULN2003 driver board. 512-step resolution per revolution, perfect for precision positioning in 3D printers, camera sliders, and clocks.",
        price: 2.99,
        discount: 0,
        stock: 130,
        image: "https://m.media-amazon.com/images/I/71M6YEzJXeL._AC_SX679_.jpg",
        featured: false,
        category: cat("motors-drivers"),
        tags: ["28byj48", "stepper", "uln2003", "unipolar"],
        specs: { Phases: "4", Steps: "512/rev", "Supply Voltage": "5V", Driver: "ULN2003 included" },
      },

      // ── WIRELESS MODULES ──────────────────────────────────────
      {
        name: "HC-05 Bluetooth Module",
        description: "Classic Bluetooth 2.0 SPP module. Master/Slave mode configurable via AT commands. UART interface, 10 m range. Ideal for wireless Arduino communication with phones and PCs.",
        price: 5.99,
        discount: 0,
        stock: 110,
        image: "https://m.media-amazon.com/images/I/61vJz0M3YZL._AC_SX679_.jpg",
        featured: false,
        category: cat("wireless-modules"),
        tags: ["hc05", "bluetooth", "spp", "uart"],
        specs: { Bluetooth: "v2.0 SPP", Range: "~10 m", Baud: "9600 (default)", "Logic Voltage": "3.3V" },
      },
      {
        name: "NRF24L01+ 2.4 GHz RF Transceiver",
        description: "Low-power 2.4 GHz ISM band RF transceiver with SPI interface, up to 250 kbps–2 Mbps data rate and 100 m range in open air. Perfect for multi-node sensor networks.",
        price: 2.49,
        discount: 0,
        stock: 200,
        image: "https://m.media-amazon.com/images/I/61cqmRBbvEL._AC_SX679_.jpg",
        featured: false,
        category: cat("wireless-modules"),
        tags: ["nrf24l01", "rf", "2.4ghz", "transceiver"],
        specs: { Frequency: "2.4 GHz", "Data Rate": "250 kbps–2 Mbps", Range: "100 m (open air)", Interface: "SPI" },
      },

      // ── DISPLAY MODULES ───────────────────────────────────────
      {
        name: "0.96\" OLED Display I2C (128×64)",
        description: "Crisp 0.96-inch SSD1306 monochrome OLED with 128×64 resolution. I2C interface (2-wire). Works at 3.3V and 5V. Contrast ratio far superior to LCDs.",
        price: 3.99,
        discount: 0,
        stock: 175,
        image: "https://m.media-amazon.com/images/I/61MHvzWqiUL._AC_SX679_.jpg",
        featured: true,
        category: cat("display-modules"),
        tags: ["oled", "ssd1306", "display", "i2c"],
        specs: { Size: "0.96 inch", Resolution: "128×64", Driver: "SSD1306", Interface: "I2C (addr 0x3C)" },
      },
      {
        name: "16×2 LCD Display with I2C Backpack",
        description: "16-character, 2-line LCD with HD44780 driver and I2C adapter pre-soldered. Blue backlight, adjustable contrast. Reduces wiring from 8+ pins to just 4.",
        price: 3.49,
        discount: 0,
        stock: 140,
        image: "https://m.media-amazon.com/images/I/71I+xBqRoYL._AC_SX679_.jpg",
        featured: false,
        category: cat("display-modules"),
        tags: ["lcd", "1602", "i2c", "hd44780"],
        specs: { Characters: "16×2", Driver: "HD44780", Interface: "I2C via PCF8574", Backlight: "Blue LED" },
      },

      // ── POWER & BATTERIES ─────────────────────────────────────
      {
        name: "TP4056 Li-Ion Charger Module (Type-C)",
        description: "1A USB Type-C lithium battery charger with DW01A protection IC (overcharge, over-discharge, short-circuit). Onboard charge and done indicator LEDs.",
        price: 1.29,
        discount: 0,
        stock: 500,
        image: "https://m.media-amazon.com/images/I/61ZKZB7XNSL._AC_SX679_.jpg",
        featured: false,
        category: cat("power-batteries"),
        tags: ["tp4056", "lithium", "charger", "usbc"],
        specs: { "Charge Current": "1A (max)", Input: "USB Type-C 5V", Protection: "DW01A included", Voltage: "4.2V cutoff" },
      },
      {
        name: "MT3608 DC-DC Boost Converter",
        description: "Step-up boost converter module adjustable from 2–24V input to up to 28V output. Up to 2A output. Ideal for powering 12V systems from a 3.7V LiPo.",
        price: 1.49,
        discount: 0,
        stock: 220,
        image: "https://m.media-amazon.com/images/I/61gR7u5WGSL._AC_SX679_.jpg",
        featured: false,
        category: cat("power-batteries"),
        tags: ["mt3608", "boost", "dc-dc", "converter"],
        specs: { Input: "2–24V", Output: "2–28V (adjustable)", "Max Current": "2A", Efficiency: "93%" },
      },
      {
        name: "LM2596 DC-DC Buck Converter",
        description: "Adjustable step-down voltage regulator with 3A output, 3–40V input, output voltage set by trimpot. Onboard LED voltmeter display. Excellent for bench power supplies.",
        price: 2.49,
        discount: 0,
        stock: 160,
        image: "https://m.media-amazon.com/images/I/71IKR0+YXBL._AC_SX679_.jpg",
        featured: false,
        category: cat("power-batteries"),
        tags: ["lm2596", "buck", "step down", "dc-dc"],
        specs: { Input: "3–40V", Output: "1.25–35V (adjustable)", "Max Current": "3A", Display: "LED voltmeter" },
      },
      {
        name: "18650 Li-Ion Battery 3500mAh (2-Pack)",
        description: "High-capacity 3.7V 3500mAh rechargeable 18650 cells. Flat-top, no PCB. Suitable for DIY power banks, robot power systems, and LED flashlights.",
        price: 8.99,
        discount: 0,
        stock: 75,
        image: "https://m.media-amazon.com/images/I/71BbQMjrL+L._AC_SX679_.jpg",
        featured: false,
        category: cat("power-batteries"),
        tags: ["18650", "lithium", "battery", "3500mah"],
        specs: { Voltage: "3.7V nominal", Capacity: "3500 mAh", Size: "18650 (flat top)", Quantity: "2 cells" },
      },

      // ── TOOLS & EQUIPMENT ─────────────────────────────────────
      {
        name: "60W Digital Soldering Iron Station",
        description: "Temperature-controlled soldering station with digital display, 200–450 °C range, ceramic heating element, and replaceable tip set. Fast heating, 30-second warm-up.",
        price: 22.99,
        discount: 5,
        stock: 30,
        image: "https://m.media-amazon.com/images/I/71u1g4J3lUL._AC_SX679_.jpg",
        featured: false,
        category: cat("tools-equipment"),
        tags: ["soldering", "iron", "station", "60w"],
        specs: { Power: "60W", "Temp Range": "200–450°C", Display: "LED digital", Warmup: "~30 sec" },
      },
      {
        name: "Digital Multimeter UT61E",
        description: "True RMS auto-ranging digital multimeter with 22000-count display. Measures AC/DC voltage, current, resistance, capacitance, frequency, diode, and continuity.",
        price: 18.99,
        discount: 0,
        stock: 25,
        image: "https://m.media-amazon.com/images/I/71K4z0EzMuL._AC_SX679_.jpg",
        featured: false,
        category: cat("tools-equipment"),
        tags: ["multimeter", "dmm", "true rms", "ut61e"],
        specs: { Display: "22000 count", "DC Voltage": "220 mV–1000V", "AC Voltage": "2.2V–750V", "True RMS": "Yes" },
      },

      // ── CABLES & CONNECTORS ───────────────────────────────────
      {
        name: "Jumper Wire Kit — 120 Pieces (M-M, F-F, M-F)",
        description: "120-piece premium breadboard jumper wire kit: 40× male-to-male, 40× female-to-female, 40× male-to-female. 20 cm length, colour-coded for fast wiring.",
        price: 3.99,
        discount: 0,
        stock: 400,
        image: "https://m.media-amazon.com/images/I/71Gec5bzDJL._AC_SX679_.jpg",
        featured: false,
        category: cat("cables-connectors"),
        tags: ["jumper", "wire", "breadboard", "dupont"],
        specs: { Quantity: "120 pcs (40 each)", Length: "20 cm", Types: "M-M, F-F, M-F", Colours: "10 colours" },
      },
      {
        name: "830-Point Solderless Breadboard",
        description: "Full-size 830-tie-point breadboard with power rails, strong adhesive backing, and colour-coded rows. Compatible with all standard DIP ICs and components.",
        price: 3.49,
        discount: 0,
        stock: 220,
        image: "https://m.media-amazon.com/images/I/81Z7jaxQTUL._AC_SX679_.jpg",
        featured: false,
        category: cat("pcb-prototyping"),
        tags: ["breadboard", "solderless", "prototyping", "830"],
        specs: { "Tie Points": "830", Rails: "4 power rails", Pitch: "2.54 mm", Adhesive: "Yes" },
      },

      // ── LEDs & LIGHTING ───────────────────────────────────────
      {
        name: "5mm LED Assortment — 300 Pieces",
        description: "300-piece 5mm LED assortment in red, green, blue, yellow, and white (60 each). 2.0–3.4V forward voltage. Ideal for indicators, RGB arrays, and educational kits.",
        price: 4.99,
        discount: 0,
        stock: 150,
        image: "https://m.media-amazon.com/images/I/71ZGh5ItDIL._AC_SX679_.jpg",
        featured: false,
        category: cat("leds-lighting"),
        tags: ["led", "5mm", "assortment", "indicator"],
        specs: { Quantity: "300 pcs (60 each)", Size: "5 mm", Colours: "Red, Green, Blue, Yellow, White", Voltage: "2.0–3.4V" },
      },
      {
        name: "WS2812B RGB LED Strip — 1 m (60 LEDs/m)",
        description: "Individually addressable 5V RGB LED strip with WS2812B ICs, 60 LEDs per metre, IP30, white PCB. Control all LEDs with a single data pin using FastLED or NeoPixel.",
        price: 8.49,
        discount: 0,
        stock: 80,
        image: "https://m.media-amazon.com/images/I/61JGJ-2fNwL._AC_SX679_.jpg",
        featured: true,
        category: cat("leds-lighting"),
        tags: ["ws2812b", "neopixel", "rgb", "addressable led"],
        specs: { IC: "WS2812B", Density: "60 LEDs/m", Length: "1 m", Voltage: "5V", "Data Pin": "Single wire" },
      },

      // ── DIY KITS ──────────────────────────────────────────────
      {
        name: "Smart Car Chassis Kit — 4WD with Motors",
        description: "Complete 4-wheel drive robot car chassis kit: acrylic frame, 4× TT DC gear motors, 4× wheels, battery holder, and motor terminals. No soldering required for assembly.",
        price: 14.99,
        discount: 10,
        stock: 45,
        image: "https://m.media-amazon.com/images/I/71f1-S6P11L._AC_SX679_.jpg",
        featured: true,
        category: cat("diy-kits"),
        tags: ["robot car", "4wd", "chassis", "kit"],
        specs: { Drive: "4WD", Motors: "4× TT DC gear", Frame: "Acrylic", Battery: "18650 holder included" },
      },
      {
        name: "Arduino Starter Kit — 200+ Components",
        description: "All-in-one starter kit with Arduino Uno R3, breadboard, 200+ components (LEDs, resistors, sensors, servo, LCD, jumper wires), and a step-by-step project booklet.",
        price: 29.99,
        discount: 15,
        stock: 35,
        image: "https://m.media-amazon.com/images/I/81e3vFDFYkL._AC_SX679_.jpg",
        featured: true,
        category: cat("diy-kits"),
        tags: ["starter kit", "arduino", "beginner", "components"],
        specs: { "Board": "Arduino Uno R3", "Components": "200+", "Projects": "15 guided", "Includes": "Breadboard, LCD, sensors" },
      },
    ];

    const createdProducts = await Product.insertMany(productsData);

    for (const c of createdCategories) {
      const count = await Product.countDocuments({ category: c._id });
      await Category.findByIdAndUpdate(c._id, { productCount: count });
    }

    return NextResponse.json({
      message: "Database seeded successfully!",
      categories: createdCategories.length,
      products: createdProducts.length,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("Seed error:", error);
    return NextResponse.json({ message: "Seeding failed", error: message }, { status: 500 });
  }
}
